server:
    port: 8080

spring:
    application:
        name: messaging-backend
    datasource:
        url: jdbc:postgresql://localhost:5432/messaging_db
        username: postgres
        password: 123
    jpa:
        hibernate:
            ddl-auto: create-drop
            # ddl-auto: update

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: files